name: Sync Laws

on:
  workflow_dispatch:
  schedule:
    - cron: "30 4 * * *"

permissions:
  contents: write

jobs:
  update-laws:
    name: Legal Pipeline
    runs-on: ubuntu-latest
    timeout-minutes: 45
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Setup Git
        run: git config --global core.longpaths true
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: "国家法律法规数据库/requirements.txt"
      - name: Install Dependencies
        run: |
          pip install -r 国家法律法规数据库/requirements.txt
          playwright install --with-deps
      - name: Process Data
        run: |
          cd 国家法律法规数据库
          python main.py --update-schema
          python main.py -c
      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v20.0.0
        with:
          globs: "国家法律法规数据库/**/*.md"
          fix: true
          config: ".markdownlint.json"
        continue-on-error: true
      - name: Commit Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git diff --staged --quiet || (
            git commit -m "feat(laws): bump [$(date -u +"%Y-%m-%dT%H:%M:%SZ")]"
            git pull --rebase --autostash origin ${{ github.ref_name }}
            git push origin ${{ github.ref_name }}
          )
