name: Update today Sukka Rulesets

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_and_commit:
    name: Build upstream and commit
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Enable long paths
        run: git config --global core.longpaths true
      - name: Checkout own repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: "recursive"

      # - name: Checkout SukkaW/Surge source
      #   uses: actions/checkout@v4
      #   with:
      #     repository: SukkaW/Surge
      #     path: Sukka Ruleset/upstream
      #     persist-credentials: false

      - name: Update submodule
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive --remote --force "Sukka Ruleset/upstream"

      - uses: pnpm/action-setup@v4
        with:
          version: 10.10.0
      - uses: actions/setup-node@v4
        with:
          node-version-file: "Sukka Ruleset/upstream/.node-version"
          cache: "pnpm"
          cache-dependency-path: "Sukka Ruleset/upstream/pnpm-lock.yaml"

      - name: Get current date
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
          echo "cst_time=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
          echo "year=$(date +'%Y')" >> $GITHUB_OUTPUT
          echo "month=$(date +'%m')" >> $GITHUB_OUTPUT
          echo "day=$(date +'%d')" >> $GITHUB_OUTPUT
          echo "hour=$(date +'%H')" >> $GITHUB_OUTPUT
          echo "minute=$(date +'%M')" >> $GITHUB_OUTPUT
          echo "second=$(date +'%S')" >> $GITHUB_OUTPUT

      - name: Download Previous Build
        uses: actions/checkout@v4
        with:
          repository: SukkaLab/ruleset.skk.moe
          persist-credentials: false
          path: previous-build-${{ github.run_id }}-${{ github.run_number }}
          token: ${{ secrets.GIT_TOKEN }}

      - name: Grab building folder
        id: paths
        run: |
          echo "output_dir=previous-build-${{ github.run_id }}-${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Setup build folder
        run: |
          if [ ! -d ${{ steps.paths.outputs.output_dir }}/.git ]; then
            echo ".git not found"
            exit 1
          fi
          rm -rf "${{ steps.paths.outputs.output_dir }}/.git"

          if [ ! -d ${{ steps.paths.outputs.output_dir }}/List ]; then
            mkdir -p "${{ steps.paths.outputs.output_dir }}/List/domainset"
            touch "${{ steps.paths.outputs.output_dir }}/List/domainset/speedtest.conf"
          fi
          echo "public directory is ready: ${{ steps.paths.outputs.output_dir }}"

      - name: Restore build process cache
        uses: actions/cache/restore@v4
        id: cache-db-restore
        with:
          path: Sukka Ruleset/upstream/.cache
          key: ${{ runner.os }}-v3-${{ steps.date.outputs.year }}-${{ steps.date.outputs.month }}-${{ steps.date.outputs.day }} ${{ steps.date.outputs.hour }}:${{ steps.date.outputs.minute }}:${{ steps.date.outputs.second }}
          restore-keys: |
            ${{ runner.os }}-v3-${{ steps.date.outputs.year }}-${{ steps.date.outputs.month }}-${{ steps.date.outputs.day }} ${{ steps.date.outputs.hour }}:${{ steps.date.outputs.minute }}:
            ${{ runner.os }}-v3-${{ steps.date.outputs.year }}-${{ steps.date.outputs.month }}-${{ steps.date.outputs.day }} ${{ steps.date.outputs.hour }}:
            ${{ runner.os }}-v3-${{ steps.date.outputs.year }}-${{ steps.date.outputs.month }}-${{ steps.date.outputs.day }}
            ${{ runner.os }}-v3-${{ steps.date.outputs.year }}-${{ steps.date.outputs.month }}-
            ${{ runner.os }}-v3-${{ steps.date.outputs.year }}-
            ${{ runner.os }}-v3-

      - name: Install dependencies
        run: pnpm install
        working-directory: Sukka Ruleset/upstream

      - name: Build rulesets
        run: pnpm run build
        working-directory: Sukka Ruleset/upstream
        env:
          PUBLIC_DIR: ${{ github.workspace }}/${{ steps.paths.outputs.output_dir }}

      - name: Check build output
        run: |
          OUTPUT_DIR="${{ steps.paths.outputs.output_dir }}"
          if [ ! -d "$OUTPUT_DIR" ]; then
            echo "Output directory '$OUTPUT_DIR' not found"
            exit 1
          fi
          if [ ! "$(ls -A "$OUTPUT_DIR")" ]; then
            echo "Output directory '$OUTPUT_DIR' is empty"
            exit 1
          fi
          if [ ! -f Sukka Ruleset/upstream/.BUILD_FINISHED ]; then
            echo "Build marker 'Sukka Ruleset/upstream/.BUILD_FINISHED' not found"
            exit 1
          fi
          echo "Output directory '$OUTPUT_DIR' exists and is not empty."

      - name: Fix relative links in generated HTML
        run: |
          OUTPUT_DIR="${{ steps.paths.outputs.output_dir }}"
          echo "Searching for HTML files in $OUTPUT_DIR to fix links..."
          find "$OUTPUT_DIR" -maxdepth 1 -name '*.html' -exec sed -i 's|href="\(List\|Clash\|sing-box\|Modules\|Mock\|Internal\|LegacyClashPremium\|Surfboard\)/|href="./\1/|g' {} +
          echo "Link fixing complete."
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-${{ github.sha }}-${{ github.run_number }}
          path: ${{ steps.paths.outputs.output_dir }}
          if-no-files-found: error
          retention-days: 1
          compression-level: 4
          include-hidden-files: false

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          cd "Sukka Ruleset/upstream"
          UPSTREAM_COMMIT_SHA=$(git rev-parse --short HEAD)
          cd ../..

          git add "Sukka Ruleset/upstream" "${{ steps.paths.outputs.output_dir }}"

          if git diff --staged --quiet; then
            echo "No changes detected in upstream submodule or rulesets. Nothing to commit."
            echo "HAS_CHANGES=false" >> $GITHUB_ENV
          else
            echo "Changes detected. Committing..."
            echo "HAS_CHANGES=true" >> $GITHUB_ENV
            git commit -m "feat(ruleset): update [${{ steps.date.outputs.cst_time }}]" -m "Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} (Upstream commit: $UPSTREAM_COMMIT_SHA)"
          fi

      - name: Push changes
        if: env.HAS_CHANGES == 'true'
        run: |
          echo "Pulling latest changes with rebase..."
          git pull --rebase origin ${{ github.ref_name }}
          echo "Pushing changes..."
          git push origin HEAD:${{ github.ref_name }}

      - name: Save build process cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: Sukka Ruleset/upstream/.cache
          key: ${{ runner.os }}-v3-${{ steps.date.outputs.year }}-${{ steps.date.outputs.month }}-${{ steps.date.outputs.day }} ${{ steps.date.outputs.hour }}:${{ steps.date.outputs.minute }}:${{ steps.date.outputs.second }}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.paths.outputs.output_dir }}

  diff_deployment_on_pr:
    if: github.event_name == 'pull_request'
    needs:
      - build_and_commit
    name: Diff output
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-artifact-${{ github.sha }}-${{ github.run_number }}
          path: public
      - name: Diff
        run: |
          git clone --filter=tree:0 --no-tags https://github.com/SukkaLab/ruleset.skk.moe.git ./deploy-git >/dev/null 2>&1
          cd ./deploy-git
          git fetch origin master >/dev/null 2>&1
          rm -rf ./*
          cp -rf ../public/* ./
          git --no-pager diff --minimal

  deploy_pages:
    name: Deploy to GitHub Pages
    needs: build_and_commit
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # deploy_to_github_dist:
  #   needs:
  #     - build_and_commit
  #   name: Deploy to GitHub Dist
  #   if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-24.04-arm
  #   steps:
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: build-artifact-${{ github.sha }}-${{ github.run_number }}
  #         path: public
  #     - name: Upload Dist to GitHub
  #       continue-on-error: true
  #       run: |
  #         gh repo unarchive SukkaLab/ruleset.skk.moe --yes
  #         git clone --filter=tree:0 --no-tags https://${GH_USER}:${GH_TOKEN}@github.com/SukkaLab/ruleset.skk.moe.git ./deploy-git
  #         cd ./deploy-git
  #         git config --global push.default matching
  #         git config --global user.email "${GH_EMAIL}"
  #         git config --global user.name "${GH_USER}"
  #         rm -rf ./*
  #         cp -rf ../public/* ./
  #         echo "ruleset.skk.moe" > CNAME
  #         git add --all .
  #         git commit -m "deploy: update [${{ steps.date.outputs.cst_time }}]"
  #         git push --quiet --force origin HEAD:master
  #         cd ..
  #         rm -rf ./deploy-git
  #         gh repo archive SukkaLab/ruleset.skk.moe --yes
  #       env:
  #         GH_EMAIL: ${{ secrets.GIT_EMAIL }}
  #         GH_USER: ${{ secrets.GIT_USER }}
  #         GH_TOKEN: ${{ secrets.GIT_TOKEN }}
