name: Bump Homebrew Formula

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  bump-formula:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Timestamp
        id: generate-timestamp
        run: |
          echo "timestamp=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
        shell: bash
      - name: Bump Mihomo Alpha Formula
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: mihomo@alpha
          formula-path: homebrew/Formula/mihomo@alpha.rb
          homebrew-tap: dearealeo/Library
          base-branch: main
          download-url: https://github.com/MetaCubeX/mihomo/archive/refs/tags/Prerelease-Alpha.tar.gz
          create-pullrequest: false
          create-branch: false
          commit-message: |
            feat(formula): update Mihomo Alpha [${{ steps.generate-timestamp.outputs.timestamp }}]
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
