name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "30 12 * * *"

permissions:
  contents: write

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.13"
          cache: "pip"
      - name: Install dependencies
        run: pip install -r 新闻联播/requirements.txt
      - name: Generate content
        run: python 新闻联播/main.py
      - name: Check for changes
        id: changed-files
        uses: tj-actions/changed-files@v46.0.5
        with:
          files: |
            **/*.md
            新闻联播/catalogue.json
          sha: ${{ github.sha }}
          since_last_remote_commit: true
      - name: Lint Markdown files
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: DavidAnson/markdownlint-cli2-action@v19.1.0
        with:
          globs: ${{ steps.changed-files.outputs.all_changed_files }}
          fix: true
          config: '{"MD013":false,"MD024":false,"MD041":false,"MD001":false,"MD007":false,"MD028":true,"MD003":false,"MD033":false}'
        continue-on-error: true
      - name: Commit and push changes
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git diff --staged --quiet || git commit -m "feat: update [$(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M:%S')]" && git push origin ${{ github.ref_name }}
