name: Update today Xinwen Lianbo

on:
  workflow_dispatch:
  schedule:
    - cron: "30 12 * * *"

jobs:
  update:
    name: Update today Xinwen Lianbo
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4.3.0
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit
      - name: Generate content
        run: npm run start
        env:
          NODE_ENV: production
      - name: Run linter to fix markdown issues
        run: npm run lint:fix
        continue-on-error: true
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Commit changes
        run: |
          git add -A
          git diff --staged --quiet || git commit -m "feat: update [$(date +'%Y-%m-%d %H:%M:%S')]"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
